<!DOCTYPE html>          
<html>       
	<head>
		<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
		<meta  charset="UTF-8">
	    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?> /css/cmeni.css"/>
	   
	    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/script/script.js"></script>	    
	</head>
	<body width="100%">		
		<?php echo $this->layout()->content ?>
	</body>
</html>
