<form name="certificateForm" method="post">
  <div align="center">
	<br>
	<br>
	<div><label>Well Done ! You have passed the test. </label></div>
	<br>
	<div>Please fill the form below to get the certificate on your email account.</div>
	<fieldset class="orderMainField">
	<fieldset class="fieldset_border_none">
		  <h2>Certificate</h2>
		<table align="left" style="width:auto">
			<tr>
				<td>
					<label>Name:</label>
				</td>
				<td class="redStar">
					<input type="text" name="Name" id="Name" size="25"/>*
				</td>
			</tr>
			<tr>
				<td>
					<label>Last Name:</label>
				</td>
				<td class="redStar">
					<input type="text" name="Tel" id="Tel" size="25"/>*
				</td>
			</tr>
			<tr>
				<td>
					<label>Location/City:</label>
				</td>
				<td class="redStar">
					<input type="text" name="Loc" id="Loc" size="25"/>*
				</td>
			</tr>
			<tr>
				<td>
					<label>Email:</label>
				</td>
				<td class="redStar">
					<input type="text" name="Email" id="Email" size="25"/>*
				</td>
			</tr>
			
		</table>
		</fieldset>
		<br/>
		<fieldset class="fieldset_border_none">
			<table>
				<tr>
					<td>	
						<input type="submit" id="submitCert" value="Submit" name="Submit"/>
					</td>		
				</tr>
			</table>
		</fieldset>
	</fieldset>
</div>	
</form>
